config/routes.rb
Eventreg::Application.routes.draw do
  get '/user/browse' => 'user#browse'
  get '/user/register' => 'user#register'
  get '/user/login' => 'user#login'
  get '/user/logout' => 'user#logout'
#  get '/user/force_register' => 'user#force_register'
#  post '/user/force_register' => 'user#force_register'
  post '/user/register' => 'user#register'
  post '/user/login' => 'user#login'
#  get '/user/reset' => 'user#reset'
  get '/user/details' => 'user#details'
  
  get '/admin' => 'admin#review'
#  get '/admin/email' => 'admin#email'
#  post '/admin/email' => 'admin#email'
#  get '/admin/force_register' => 'admin#force_register'  
#  post '/admin/force_register' => 'admin#force_register'  
  get '/admin/force/:type/:id' => 'admin#force'
  post '/admin/force/:type/:id' => 'admin#force'
  get '/admin/export' => 'admin#export'
  get '/admin/export_workshops' => 'admin#export_workshops'
  
  match '/user/description/:id' => 'user#ajaxDescription', :via => [:post]

  root :to => 'user#login'

  get '/errors/file_not_found'
  get '/errors/unprocessable'
  get '/errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :workshops
  
  def self.authenticate(p, n)
    u = User.where(prefix: p, number: n).first
    return u.id unless u.nil?
  end
  
  def self.boys
    where("division = 'BD'")
  end
  
  def self.girls
    where("division = 'GD'")
  end

  def self.students
    where("role = 'student'");
  end

  def self.teachers
    where("role = 'teacher'");
  end
  
  def self.registered
    self.all.select {|s| s.done?}
  end
  
  def self.unregistered
    self.all.select {|s| !(s.done?)}
  end
  
  def sessions_needed
    [1,2,3] - workshops.map(&:session)
  end

  def done?
    sessions_needed.empty?
  end
  
  def has_first?
    workshops.collect {|w| w.session}.include? 1
  end
  
  def first
    workshops.select {|w| w.session == 1}[0]
  end
  
  def has_second?
    workshops.collect {|w| w.session}.include? 2
  end
  
  def second
    workshops.select {|w| w.session == 2}[0]
  end
  
  def has_third?
    workshops.collect {|w| w.session}.include? 3
  end
  
  def third
    workshops.select {|w| w.session == 3}[0]
  end
  
  def to_s
    full
  end

  # Idea: move these settings to a new table
  def reg_time
    if self.role == "student"
      return Time.new(2018, 2, 26, 7, 45, 00, "-07:00") if self.special == "DAG"
      return Time.new(2018, 2, 26, 9, 30, 00, "-07:00") if self.year == 12
      return Time.new(2018, 2, 26, 14, 45, 00, "-07:00") if self.year == 11
      return Time.new(2018, 2, 27, 8, 0, 00, "-07:00") if self.year == 10
      return Time.new(2018, 2, 28, 9, 30, 00, "-07:00") if self.year == 9
    else
      return Time.new(2018, 2, 26, 9, 30, 00, "-07:00")
    end
  end
  
  def can_register
    return Time.now > self.reg_time
  end
  
end

app/views/admin/_workshop_selector_force.html.erb
<div style="float: left;">
  <%= form_tag(:controller => "admin", :action => "force") do %>
  <% if user.has_first? %>

    <span class="done">First Session: <%= (user.first.name + " &#10003;").html_safe %> </span> <br />
  <span class="leader done">1</span>
  <%= select(:user, :first, Workshop.firsts.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove First Workshop", :name => "rmfirst" %>
  <br /><br />

<% else %>
    <span class="leader not-done">1</span>
  <%= select(:user, :first, Workshop.firstsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />

  <% end %>

  <% if user.has_second? %>

    <span style="color: green;">Second Session: <%= (user.second.name + " &#10003;").html_safe %></span> <br />
  <span class="leader done">2</span>
  <%= select(:user, :second, Workshop.seconds.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove Second Workshop", :name => "rmsecond" %>
  <br /><br />

<% else %>

    <span class="leader not-done">2</span>
  <%= select(:user, :second, Workshop.secondsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />

<% end %>

  <% if user.has_third? %>

    <span style="color: green;">Third Session: <%= (user.third.name + " &#10003;").html_safe %></span> <br />
  <span class="leader done">3</span>
  <%= select(:user, :third, Workshop.thirds.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove Third Workshop", :name => "rmthird" %>
  <br /><br />

<% else %>

    <span class="leader not-done">3</span>
  <%= select(:user, :third, Workshop.thirdsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />
<% end %>
  <br />

<!-- <span class="not-done">Registration has now closed!</span> -->
<%= submit_tag "Confirm Selection" %>

</div>

<div style="float: left; width: 350px; margin: 20px;">
  <h3 id="presentor"></h3>
  <div id="description" style="font-size: 0.9em;">
  </div>
</div>

<% end %>

app/views/admin/email.html.erb
<style type="text/css">
  .text{font-family: Verdana, Geneva, sans-serif;}
  .text label{font-size: 1.5em;}
  h1 {font-size: 2.5em;}
  td {
    border-bottom: dashed;
    padding: 5px;
  }
  table {padding:10px;}
  select {width: 45em;}
</style>

<% content_for(:head) do %>
<% javascript_include_tag :register %>
<% end %>

<%= form_tag(:action => "email") do %>

<label for="email_body">To:</label><br />
<%= text_field("email","to",:size => 80, :placeholder => "Enter student or teacher prefixes here separated by commas, or ALL/STUDENTS/TEACHERS.") %>
<br />
<label for="email_title">Title:</label><br />
<%= text_field("email", "title", :size => 80, :placeholder => "RJHS Diversity Day Registration")%>
<br />
<label for="email_body">Body:</label><br />
<%= text_area("email","body",:size => "120x20", :placeholder => "Enter the text of your e-mail here.  It will be formatted automagically." )%>
<br /><br />
<%= submit_tag("Send", confirm: "Are you sure you wanted to press the button? E-mail will be sent.") %>

<% end %>

app/views/admin/force.html.erb
<style>
body
{
background-image:url('/assets/earth.png');
background-repeat:no-repeat;
background-attachment:fixed;
background-position: right bottom;
}
</style>
<style type="text/css">
.text{
  font-family: Verdana, Geneva, sans-serif;
}
.text label{
  font-size: 1.5em;
}
h1 {
  font-size: 2.5em;
}
td {
  border-bottom: dashed;
  padding: 5px;
}
table {
  padding:10px;
}
select {
  width: 45em;
}

</style>

<% content_for(:head) do %>
  <% javascript_include_tag :register %>
<% end %>

<p class="text">Currently editing registration info for <%= user.full %>.  <%= link_to "Return to admin homepage.", "/admin" %></p>

<p class="text">Click on a workshop to see its description. Press submit to assign the student to the selected workshops.  Note that this process is "legal" in that it will maintain gender limits and availability and yell at you if something is wrong.</p>

<div style="float: left;">
  <%= form_tag(:controller => "admin", :action => "force") do %>
  <% if user.has_first? %>
  
  <span class="done">First Session: <%= (user.first.name + " &#10003;").html_safe %> </span> <br />
  <span class="leader done">1</span>
  <%= select(:user, :first, Workshop.firsts.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove First Workshop", :name => "rmfirst" %>
  <br /><br />
  
  <% else %>
  <span class="leader not-done">1</span>
  <%= select(:user, :first, Workshop.firstsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />
  
  <% end %>
  
  <% if user.has_second? %>
  
  <span style="color: green;">Second Session: <%= (user.second.name + " &#10003;").html_safe %></span> <br />
  <span class="leader done">2</span>
  <%= select(:user, :second, Workshop.seconds.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove Second Workshop", :name => "rmsecond" %>
  <br /><br />
  
  <% else %>
  
  <span class="leader not-done">2</span>
  <%= select(:user, :second, Workshop.secondsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />
  
  <% end %>
  
  <% if user.has_third? %>
  
  <span style="color: green;">Third Session: <%= (user.third.name + " &#10003;").html_safe %></span> <br />
  <span class="leader done">3</span>
  <%= select(:user, :third, Workshop.thirds.collect {|w| [w.name, w.id]}, {}, {:size => "6", :disabled => "true"}) %>
  <br />
  <%= submit_tag "Remove Third Workshop", :name => "rmthird" %>
  <br /><br />
  
  <% else %>
  
  <span class="leader not-done">3</span>
  <%= select(:user, :third, Workshop.thirdsAvailable(user).collect {|w| [w.name, w.id]}, {}, {:size => "6"}) %>
  <br /><br />
  <% end %>
  <br />
  
  <!-- <span class="not-done">Registration has now closed!</span> -->
  <%= submit_tag "Confirm Selection" %>
  
</div>

<div style="float: left; width: 350px; margin: 20px;">
  <h3 id="presentor"></h3>
  <div id="description" style="font-size: 0.9em;">
  </div>
</div>

<% end %>

app/views/admin/force_register.html.erb
<style type="text/css">
  .text{font-family: Verdana, Geneva, sans-serif;}
  .text label{font-size: 1.5em;}
  h1 {font-size: 2.5em;}
  td {
    border-bottom: dashed;
    padding: 5px;
  }
  table {padding:10px;}
  select {width: 45em;}
</style>

<% content_for(:head) do %>
<% javascript_include_tag :register %>
<% end %>

<% if user.class == Teacher %>
<br />
<%= button_to "The 'Oops, Drew and Matt and Chris and Lindsay Goofed' Workshop Reset Button", '/user/reset', method: 'get', data: { confirm: 'Are you sure?  This will clear the workshops for which you have registered!' } %>
<% end %>

<% if user.done? %>
<p class="text">You are registered for:
  <br />
  <table>
    <tr>
      <td> Session </td>
      <td> Name </td>
      <td> Presentor </td>
      <td> Description </td>
      <td> Location </td>
      <% user.workshops.each do |w|  %>
    <tr>
      <td> <%= w.session %> </td>
      <td> <%= w.name %> </td>
      <td> <%= w.presentor %> </td>
      <td> <%= w.description %> </td>
      <td> <%= w.room %> </td>      
    </tr>
    <% end %>
  </table>
</p>
<% else %>

<p class="text">Click on a workshop to see its description. Press submit to sign up for the highlited workshops.</p>
<div style="float: left;">
  <%= form_tag(:controller => "user", :action => "register") do %>
<br />

<% if user.has_first? %>

<span style="color: green;">First Session: <%= (user.first.name + " &#10003;").html_safe %> </span> <br />
<%= select(:user, :first, Workshop.firsts.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6", :disabled => "true", :selected => params[:user][:first]}) %>
<br /><br />

<% else %>

First Session<br />
<%= select(:user, :first, Workshop.firsts.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6"}) %>
<br /><br />

<% end %>

<% if user.has_second? %>

<span style="color: green;">Second Session: <%= (user.second.name + " &#10003;").html_safe %></span> <br />
<%= select(:user, :second, Workshop.seconds.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6", :disabled => "true", :selected => params[:user][:second]}) %>
<br /><br />

<% else %>

Second Session<br />
<%= select(:user, :second, Workshop.seconds.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6"}) %>
<br /><br />

<% end %>

<% if user.has_third? %>

<span style="color: green;">Third Session: <%= (user.third.name + " &#10003;").html_safe %></span> <br />
<%= select(:user, :third, Workshop.thirds.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6", :disabled => "true", :selected => params[:user][:third]}) %>
<br /><br />

<% else %>

Third Session<br />
<%= select(:user, :third, Workshop.thirds.collect {|w| ["#{w.name} - #{w.ttaken}/#{w.tlimit}, id: #{w.id}", w.id]}, {}, {:size => "6"}) %>
<br /><br />
<% end %>
<%= submit_tag("Submit") %>
<br />

</div>

<div style="float: left; width: 350px; margin: 20px;">
<h3 id="presentor"></h3>
<div id="description" style="font-size: 0.9em;">
</div>
</div>

<div>
</div>
<% end %>

<% end %>

app/views/admin/review.html.erb
<h1>Review Event Registration Status</h1>
<%= link_to "Export Event Registration Info", "/admin/export", :style => "font-size: 1.5em;" %> 
<%= link_to "Export Workshop Popularity Info", "/admin/export_workshops", :style => "font-size: 1.5em; margin-left: 3em;" %>
<div style="margin-top: 2em;">
  <div style="font-size: 1.3em; float: left;  ">
    <h3><%= "Teachers registered: #{@tregistered} of #{@tall}" %></h3>
    <h3><%= "Boys Division: #{@tboysdone} of #{@tboysall}" %></h3>
    <h3><%= "Girls Division: #{@tgirlsdone} of #{@tgirlsall}" %></h3>
    <h3><%= "Incomplete Teacher Registrations: #{@tUnfinished}" %></h3>
  </div>
  <div style="font-size: 1.3em; float: left; ">
    <h3><%= "Students registered: #{@sregistered} of #{@sall}" %></h3>
    <h3><%= "Boys Division: #{@sboysdone} of #{@sboysall}" %></h3>
    <h3><%= "Girls Division: #{@sgirlsdone} of #{@sgirlsall}" %></h3>
    <h3><%= "Incomplete Student Registrations: #{@sUnfinished}" %></h3>
    <br />
  </div>
  <div style="clear: both;"></div>
  <style>
    #admin-table tr:nth-child(even) {background: #CCC}
    #admin-table tr:nth-child(odd) {background: #FFF}
  </style>
  <div style="font-size: 1.3em;  ">
    Tips for navigating: Search for student name with Cmd-f or Ctrl-f
    <br />
    "Stuck" students are marked (Stuck), so you could search for that the same way.
  </div>
  <br />
  <br />
  <table id="admin-table" style="height: 10em; width: 50%;">
    <!-- BD students -->
    <% @sboys.each do |s| %>
    <% if s.workshop_ids.count != 0 and s.workshop_ids.count != 3 %>
    <tr style="color: red;">
      <td><%= link_to (s.full + "(Stuck)"), "/admin/force/student/#{s.id}" %></td>
      <% else %>
    <tr>
      <td><%= link_to s.full, "/admin/force/student/#{s.id}" %></td>
      <% end %>
        <td><%= s.prefix %></td>
      <td><%= s.first.nil? ? "None" : s.first %></td>
      <td><%= s.second.nil? ? "None" : s.second %></td>
      <td><%= s.third.nil? ? "None" : s.third %></td>
    </tr>
    <% end %>
    <!-- GD students -->
    <% @sgirls.each do |s| %>
    <% if s.workshop_ids.count != 0 and s.workshop_ids.count != 3 %>
    <tr style="color: red;">
      <td><%= link_to (s.full + "(Stuck)"), "/admin/force/student/#{s.id}" %></td>
      <% else %>
    <tr>
          <td><%= link_to s.full, "/admin/force/student/#{s.id}" %></td>
	  <% end %>
          <td><%= s.prefix %></td>
          <td><%= s.first.nil? ? "None" : s.first %></td>
          <td><%= s.second.nil? ? "None" : s.second %></td>
          <td><%= s.third.nil? ? "None" : s.third %></td>
    </tr>
    <% end %>
    <!-- BD teachers -->
    <% @tboys.each do |t| %>
    <% if t.workshop_ids.count != 0 and t.workshop_ids.count != 3 %>
    <tr style="color: red;">
      <td><%= link_to (t.full + "(Stuck)"), "/admin/force/teacher/#{t.id}" %></td>
      <% else %>
    <tr>
      <td><%= link_to t.full, "/admin/force/teacher/#{t.id}" %></td>
      <% end %>
      <td><%= t.prefix %></td>
      <td><%= t.first.nil? ? "None" : t.first %></td>
      <td><%= t.second.nil? ? "None" : t.second %></td>
      <td><%= t.third.nil? ? "None" : t.third %></td>
    </tr>
    <% end %>
    <!-- GD teachers -->
    <% @tgirls.each do |t| %>
    <% if t.workshop_ids.count != 0 and t.workshop_ids.count != 3 %>
    <tr style="color: red;">
      <td><%= link_to (t.full + "(Stuck)"), "/admin/force/teacher/#{t.id}" %></td>
      <% else %>
    <tr>
      <td><%= link_to t.full, "/admin/force/teacher/#{t.id}" %></td>
      <% end %>
      <td><%= t.prefix %></td>
      <td><%= t.first.nil? ? "None" : t.first %></td>
      <td><%= t.second.nil? ? "None" : t.second %></td>
      <td><%= t.third.nil? ? "None" : t.third %></td>
    </tr>
    <% end %>
  </table>
  <br />
</div>